In [1]:
import numpy as np
import pandas as pd

In [2]:
ads = pd.read_csv('Social_Network_Ads.csv')
ads

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [3]:
ads.describe()

            User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [4]:
ads.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
X = ads.drop(['User ID','Gender','Purchased'],axis=1)
X

      Age  EstimatedSalary
0    19.0          19000.0
1    35.0          20000.0
2    26.0          43000.0
3    27.0          57000.0
4    19.0          76000.0
..    ...              ...
395  46.0          41000.0
396  51.0          23000.0
397  50.0          20000.0
398  36.0          33000.0
399  49.0          36000.0

[400 rows x 2 columns]

In [7]:
y = ads['Purchased']
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [15]:
X_train

array([[ 1.8925893 ,  1.52189404],
       [ 0.1250379 ,  0.03213212],
       [ 0.9106163 , -1.31157471],
       [-1.34792161, -1.48684082],
       [-0.169554  , -0.58129926],
       [-0.56234321,  2.33980255],
       [ 1.0088136 , -1.19473064],
       [-0.75873781,  1.08372877],
       [ 2.1871812 , -1.04867555],
       [ 0.0268406 , -0.25997806],
       [-0.46414591, -1.1363086 ],
       [ 0.1250379 ,  0.03213212],
       [ 1.6961947 , -0.90262046],
       [ 1.1070109 , -0.90262046],
       [ 0.5178271 ,  1.22978386],
       [-1.05332971, -1.4576298 ],
       [-1.15152701, -1.54526286],
       [-0.0713567 ,  0.67477452],
       [ 0.4196298 , -0.46445519],
       [-0.2677513 , -0.25997806],
       [-0.85693511,  0.14897619],
       [ 0.0268406 ,  0.29503128],
       [ 0.7142217 , -1.28236369],
       [ 1.5979974 ,  1.11293979],
       [ 0.812419  , -1.36999675],
       [-1.44611891, -1.22394166],
       [-0.0713567 ,  0.14897619],
       [ 0.4196298 , -0.14313399],
       [-0.2677513 ,  0.03213212],
       [ 1.3034055 ,  2.22295848],
       [ 0.1250379 ,  0.76240757],
       [-1.34792161,  0.55793045],
       [ 1.9907866 ,  0.73319655],
       [-1.24972431, -1.39920777],
       [ 0.3214325 , -0.3184001 ],
       [-0.95513241,  0.55793045],
       [ 0.4196298 ,  0.29503128],
       [ 0.4196298 ,  1.11293979],
       [ 0.812419  ,  0.76240757],
       [ 0.9106163 ,  1.25899488],
       [-0.46414591, -1.22394166],
       [-1.83890811, -1.31157471],
       [ 1.1070109 ,  0.55793045],
       [-0.66054051, -1.60368489],
       [-0.75873781,  0.26582026],
       [ 1.0088136 ,  2.07690339],
       [-0.56234321,  1.37583895],
       [-0.0713567 ,  0.03213212],
       [-1.93710541,  0.47029739],
       [ 0.4196298 ,  0.26582026],
       [-1.05332971,  0.41187535],
       [ 0.2232352 , -0.14313399],
       [ 1.8925893 ,  0.11976517],
       [-1.15152701, -1.60368489],
       [-1.15152701,  0.29503128],
       [-0.85693511, -0.78577639],
       [-0.46414591,  2.31059153],
       [ 0.1250379 , -0.8149874 ],
       [ 1.5979974 ,  0.99609572],
       [-0.169554  , -1.07788657],
       [ 0.812419  , -1.10709759],
       [ 0.2232352 ,  2.1061144 ],
       [-0.0713567 , -0.23076704],
       [-0.85693511,  2.28138051],
       [-0.0713567 , -0.37682213],
       [-0.2677513 , -0.58129926],
       [ 0.4196298 , -0.49366621],
       [-0.2677513 , -0.93183148],
       [ 0.3214325 , -1.16551962],
       [ 0.2232352 ,  0.06134314],
       [-1.15152701, -1.60368489],
       [-0.66054051, -0.05550093],
       [-0.2677513 , -0.49366621],
       [-0.2677513 , -1.31157471],
       [-0.75873781,  0.55793045],
       [ 0.3214325 ,  0.06134314],
       [-0.95513241,  1.55110506],
       [ 0.812419  ,  0.35345332],
       [-1.54431621, -0.20155602],
       [ 0.7142217 , -1.39920777],
       [-0.75873781, -0.61051028],
       [-0.36594861, -1.31157471],
       [ 0.2232352 ,  0.14897619],
       [-0.56234321,  1.37583895],
       [-1.44611891,  0.35345332],
       [-1.15152701,  0.29503128],
       [ 1.0088136 ,  1.7847932 ],
       [ 2.0889839 ,  2.13532542],
       [-0.2677513 , -0.43524417],
       [-0.36594861, -0.78577639],
       [ 0.1250379 , -0.25997806],
       [-1.05332971,  0.76240757],
       [ 2.1871812 ,  0.38266434],
       [-1.34792161, -0.43524417],
       [ 1.9907866 ,  2.16453644],
       [ 1.4998001 ,  0.99609572],
       [-0.2677513 ,  0.26582026],
       [-0.169554  ,  0.85004063],
       [ 1.8925893 , -0.28918908],
       [-0.0713567 ,  1.96005931],
       [-0.46414591, -0.78577639],
       [ 0.3214325 ,  0.03213212],
       [ 1.4016028 , -1.42841878],
       [ 1.4016028 ,  2.33980255],
       [-0.0713567 ,  0.0029211 ],
       [-1.15152701,  0.41187535],
       [-1.15152701,  0.06134314],
       [-1.15152701, -0.52287722],
       [ 0.3214325 , -0.28918908],
       [-0.66054051, -0.11392297],
       [-0.0713567 ,  2.16453644],
       [ 0.0268406 , -0.25997806],
       [-0.66054051, -1.04867555],
       [ 0.4196298 ,  0.14897619],
       [ 0.812419  ,  1.37583895],
       [-0.169554  , -0.52287722],
       [ 0.0268406 ,  0.03213212],
       [ 1.1070109 ,  0.52871943],
       [ 1.8925893 , -1.07788657],
       [ 1.0088136 ,  1.98927033],
       [ 0.9106163 , -0.58129926],
       [-0.46414591, -0.02628992],
       [-0.0713567 ,  2.22295848],
       [-1.74071081,  0.35345332],
       [ 0.2232352 , -0.66893231],
       [-0.2677513 , -1.39920777],
       [-1.74071081, -0.99025351],
       [ 0.7142217 , -0.72735435],
       [-1.15152701, -0.78577639],
       [ 1.9907866 ,  0.90846266],
       [ 0.2232352 , -0.37682213],
       [ 0.0268406 ,  1.22978386],
       [-0.0713567 ,  0.29503128],
       [ 1.1070109 , -1.22394166],
       [-0.169554  ,  0.14897619],
       [ 0.3214325 ,  0.06134314],
       [-0.2677513 , -0.28918908],
       [ 0.5178271 ,  1.72637117],
       [ 0.3214325 ,  0.49950841],
       [ 0.0268406 ,  1.25899488],
       [ 1.9907866 , -1.36999675],
       [-1.15152701, -1.10709759],
       [-0.56234321, -1.51605184],
       [ 0.3214325 , -0.52287722],
       [-0.66054051, -1.51605184],
       [-0.2677513 ,  0.52871943],
       [ 1.0088136 , -1.01946453],
       [-1.05332971,  0.55793045],
       [-0.2677513 ,  0.79161859],
       [ 0.4196298 ,  0.09055416],
       [-1.64251351, -0.05550093],
       [ 0.3214325 ,  0.06134314],
       [-0.46414591, -0.28918908],
       [ 0.1250379 ,  1.87242626],
       [-0.95513241,  0.41187535],
       [ 0.812419  ,  0.52871943],
       [-1.34792161, -0.34761112],
       [-0.66054051,  1.40504997],
       [ 1.2052082 ,  0.52871943],
       [-1.74071081,  0.35345332],
       [-0.56234321,  1.90163728],
       [-1.74071081,  0.47029739],
       [-0.2677513 , -1.25315268],
       [-0.85693511, -0.78577639],
       [-1.64251351,  0.52871943],
       [-0.2677513 , -0.3184001 ],
       [ 0.7142217 , -1.10709759],
       [ 2.1871812 , -0.8149874 ],
       [-0.2677513 ,  0.61635248],
       [-0.2677513 , -0.75656537],
       [-1.93710541, -0.75656537],
       [ 0.4196298 ,  2.31059153],
       [ 0.7142217 ,  0.26582026],
       [ 0.2232352 , -0.28918908],
       [-1.34792161, -1.36999675],
       [-0.46414591, -0.55208824],
       [ 0.4196298 ,  0.0029211 ],
       [ 1.6961947 ,  1.75558219],
       [ 1.2052082 , -0.75656537],
       [ 1.0088136 ,  1.43426099],
       [-1.83890811,  0.17818721],
       [ 0.3214325 ,  0.06134314],
       [ 0.2232352 ,  0.03213212],
       [-1.05332971,  0.52871943],
       [-0.169554  ,  1.63873811],
       [-0.2677513 ,  0.14897619],
       [-0.2677513 , -0.34761112],
       [-0.36594861,  1.31741692],
       [-0.2677513 ,  0.09055416],
       [ 2.1871812 ,  1.11293979],
       [-1.24972431,  0.49950841],
       [-1.05332971, -0.46445519],
       [-1.64251351, -1.57447387],
       [-0.0713567 ,  0.11976517],
       [-0.2677513 , -0.90262046],
       [ 1.5979974 ,  0.0029211 ],
       [ 0.9106163 , -1.16551962],
       [ 0.0268406 , -0.58129926],
       [-0.2677513 ,  2.25216949],
       [-0.2677513 ,  0.20739823],
       [ 0.3214325 ,  0.26582026],
       [-0.0713567 , -1.07788657],
       [ 2.1871812 , -0.69814333],
       [-0.95513241, -0.3184001 ],
       [-1.44611891, -0.11392297],
       [-1.44611891, -0.20155602],
       [-0.75873781, -1.54526286],
       [-1.24972431, -1.07788657],
       [ 2.0889839 ,  0.38266434],
       [ 1.9907866 , -0.93183148],
       [-1.93710541,  0.35345332],
       [ 0.812419  , -0.3184001 ],
       [-1.05332971, -1.54526286],
       [ 1.9907866 , -0.66893231],
       [ 1.0088136 , -1.16551962],
       [ 1.1070109 , -0.14313399],
       [ 1.2052082 , -0.99025351],
       [ 1.4998001 ,  0.06134314],
       [ 0.2232352 , -0.37682213],
       [ 1.4016028 ,  1.2882059 ],
       [ 2.0889839 , -0.8149874 ],
       [-0.169554  , -0.20155602],
       [ 0.4196298 ,  0.99609572],
       [-0.0713567 , -0.52287722],
       [ 1.0088136 , -1.07788657],
       [ 2.0889839 , -1.19473064],
       [-0.0713567 ,  0.26582026],
       [ 0.2232352 , -0.25997806],
       [ 1.1070109 ,  0.11976517],
       [-1.24972431,  0.58714146],
       [-0.75873781, -1.60368489],
       [ 0.2232352 ,  0.23660925],
       [-1.34792161,  0.41187535],
       [ 0.0268406 , -0.58129926],
       [ 0.7142217 ,  1.7847932 ],
       [-1.64251351,  0.06134314],
       [-0.2677513 , -1.36999675],
       [-0.2677513 , -1.4576298 ],
       [-0.66054051,  0.55793045],
       [-0.75873781,  0.29503128],
       [ 0.9106163 , -0.66893231],
       [-1.05332971,  0.58714146],
       [-0.2677513 ,  0.06134314],
       [-0.75873781,  1.34662793],
       [ 0.1250379 ,  1.52189404],
       [-0.85693511,  0.38266434],
       [ 0.3214325 , -0.20155602],
       [ 1.0088136 ,  0.58714146],
       [ 0.0268406 , -0.3184001 ],
       [-0.56234321, -1.51605184],
       [ 0.1250379 ,  0.14897619],
       [-1.15152701,  0.3242423 ],
       [ 0.1250379 ,  1.05451775],
       [-1.54431621, -0.43524417],
       [-0.169554  ,  1.40504997],
       [ 2.1871812 , -0.8149874 ],
       [-0.95513241, -0.43524417],
       [ 1.3034055 ,  1.87242626],
       [ 1.1070109 , -1.22394166],
       [-0.169554  , -0.28918908],
       [ 1.794392  ,  0.99609572],
       [-1.05332971, -0.34761112],
       [-1.34792161, -1.10709759],
       [-0.36594861,  0.06134314],
       [-0.95513241, -1.10709759],
       [ 1.2052082 , -1.4576298 ],
       [-0.46414591, -0.84419842],
       [-0.85693511, -0.66893231],
       [-1.54431621, -1.51605184],
       [-0.75873781,  1.90163728],
       [ 0.9106163 ,  1.02530673],
       [ 0.812419  ,  0.26582026],
       [ 1.0088136 ,  1.87242626],
       [ 0.9106163 , -0.61051028],
       [ 1.1070109 ,  2.07690339],
       [-0.56234321,  0.87925164],
       [ 0.0268406 ,  0.03213212],
       [-1.83890811, -1.28236369],
       [-0.0713567 ,  0.20739823],
       [ 0.9106163 , -0.55208824],
       [ 0.2232352 , -0.37682213],
       [-0.169554  ,  1.6095271 ],
       [-1.74071081,  0.11976517],
       [-0.66054051, -0.34761112],
       [ 0.3214325 , -0.72735435],
       [ 0.4196298 , -0.46445519],
       [-0.95513241, -0.96104249],
       [ 0.1250379 ,  0.09055416],
       [-0.95513241,  0.44108637],
       [ 0.0268406 , -0.55208824],
       [ 0.9106163 , -0.78577639],
       [-0.0713567 ,  0.06134314],
       [ 1.1070109 , -0.99025351],
       [ 0.7142217 , -1.39920777],
       [-0.2677513 ,  0.06134314],
       [-1.34792161, -1.25315268],
       [-1.15152701, -1.01946453],
       [ 0.5178271 ,  1.84321524],
       [ 0.1250379 ,  0.20739823],
       [-0.56234321,  0.47029739]])

In [16]:
y_train

247    1
110    0
16     1
66     0
153    0
      ..
71     0
106    0
270    0
348    0
102    0
Name: Purchased, Length: 300, dtype: int64

In [17]:
X_test

array([[ 0.75872215, -1.41078892],
       [ 1.9109871 ,  0.5590031 ],
       [-0.83672162, -0.75419158],
       [ 0.93599368,  0.79776576],
       [-0.74808586, -1.23171691],
       [-0.65945009, -0.21697557],
       [ 0.84735791,  1.12606443],
       [-0.74808586,  0.40977643],
       [ 0.22690756,  0.17101376],
       [ 0.40417909, -0.12743957],
       [-0.21627127, -0.12743957],
       [ 1.37917251, -1.05264491],
       [-1.27990045, -0.63481024],
       [-1.54580774, -1.38094358],
       [-0.65945009,  0.52915776],
       [-0.21627127,  1.15590977],
       [ 1.29053674, -0.93326358],
       [ 0.75872215,  0.14116843],
       [ 0.13827179, -0.81388224],
       [ 1.6450798 , -0.27666624],
       [-1.36853621, -1.26156225],
       [-0.74808586,  0.32024043],
       [ 0.84735791, -1.38094358],
       [ 1.9109871 ,  0.20085909],
       [-1.63444351, -1.50032492],
       [ 1.20190098, -1.38094358],
       [ 0.40417909,  0.32024043],
       [-0.03899974, -0.48558358],
       [ 1.55644404,  1.66328044],
       [-1.63444351, -1.44063425],
       [ 0.75872215, -0.84372758],
       [-1.63444351,  0.02178709],
       [-0.1276355 ,  2.23034177],
       [-0.83672162,  0.2903951 ],
       [ 0.22690756,  1.12606443],
       [-0.21627127,  0.17101376],
       [-0.03899974, -0.42589291],
       [ 0.04963603, -0.12743957],
       [-1.01399315, -1.17202625],
       [-1.72307927, -0.03790357],
       [ 0.93599368, -1.08249025],
       [-1.19126468, -0.42589291],
       [-1.72307927, -0.51542891],
       [ 0.84735791, -1.47047958],
       [-1.54580774, -0.60496491],
       [ 0.58145062,  2.08111511],
       [-0.74808586, -0.24682091],
       [-0.57081433,  0.05163243],
       [ 0.93599368, -0.84372758],
       [-0.30490703, -0.78403691],
       [-1.10262892,  0.2903951 ],
       [ 1.37917251,  0.3799311 ],
       [ 0.04963603, -0.42589291],
       [-1.10262892,  0.32024043],
       [-0.03899974,  0.32024043],
       [-0.92535739, -1.14218091],
       [ 1.99962286,  0.97683777],
       [-1.01399315,  1.4543631 ],
       [-0.57081433,  0.14116843],
       [-0.57081433,  0.20085909],
       [ 0.31554332, -0.54527424],
       [-0.21627127, -0.36620224],
       [ 1.29053674,  0.61869376],
       [-0.83672162,  0.52915776],
       [-0.83672162, -0.30651158],
       [-0.92535739,  2.02142444],
       [ 0.40417909,  0.61869376],
       [ 0.84735791,  2.23034177],
       [ 0.13827179, -0.30651158],
       [-0.3935428 ,  1.30513643],
       [ 1.29053674,  2.05126977],
       [-1.63444351,  0.4694671 ],
       [-0.92535739, -0.33635691],
       [-1.27990045, -1.47047958],
       [ 0.84735791, -1.05264491],
       [-0.21627127, -0.57511958],
       [ 1.6450798 ,  1.9020431 ],
       [ 1.46780827, -1.29140758],
       [-0.21627127, -0.66465558],
       [-0.03899974,  0.26054976],
       [-0.92535739, -0.36620224],
       [ 0.75872215, -1.23171691],
       [ 0.13827179,  1.93188844],
       [ 0.58145062, -0.90341825],
       [ 1.73371557, -1.29140758],
       [-0.48217856,  1.51405377],
       [ 0.31554332, -0.51542891],
       [ 0.93599368,  0.14116843],
       [-1.01399315,  0.49931243],
       [-1.36853621,  0.35008576],
       [ 1.02462945,  0.49931243],
       [-0.1276355 , -0.45573824],
       [ 0.22690756, -0.30651158],
       [ 0.31554332,  0.32024043],
       [-1.01399315, -1.58986092],
       [ 0.13827179,  0.2903951 ],
       [ 1.9109871 ,  1.8125071 ],
       [ 0.40417909, -0.15728491],
       [ 1.37917251,  2.20049644],
       [-0.30490703,  1.2752911 ]])

In [18]:
y_test

209    0
280    1
33     0
210    1
93     0
      ..
314    0
373    1
380    0
239    1
75     1
Name: Purchased, Length: 100, dtype: int64

In [19]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [20]:
y_pred = model.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,classification_report

In [31]:
print(confusion_matrix(y_test,y_pred))

[[61  2]
 [12 25]]

In [29]:
print(accuracy_score(y_test,y_pred))

0.86

In [30]:
print(precision_score(y_test,y_pred))

0.9259259259259259

In [28]:
print(recall_score(y_test,y_pred))

0.6756756756756757

In [27]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.97      0.90        63
           1       0.93      0.68      0.78        37

    accuracy                           0.86       100
   macro avg       0.88      0.82      0.84       100
weighted avg       0.87      0.86      0.85       100